apiVersion: v1
kind: Pod
metadata:
  name: jj-mongo-client
  namespace: mongodb
spec:
  containers:
  - name: my-mongo-client
    image: mongo:latest
    command: ["tail", "-f", "/dev/null"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

